Preliminary cut of bash selected with all (hopefully?) features and tests but possibly waiting for new Test::Expect:: type module

diff --git a/experimental/selected b/experimental/selected
--- a/experimental/selected
+++ b/experimental/selected
@@ -5,7 +5,10 @@
 =head1 NAME
 
 selected - a text filter extension of select that allows
-multiple selections
+multiple selections.  Depending on options menu items
+can be selected more than once and output defaults to order
+of user selection but can be in order of menu items.  '*'
+specifies selecting all menu items unless disallowed with B<-n>.
 
 =head1 SYNOPSIS
 
@@ -38,6 +41,11 @@ from the closed pipe and no menu item is selected.  Instead do:
 to get the menu from the output of the ls command (or some other).
 Menu items are separated by end of line to allow embedded horizontal
 space.
+
+=item B<-n>
+
+Disallow '*' selection of all items and require that selections
+be individually specified items by number.
 
 =item B<-s>
 
@@ -77,17 +85,23 @@ END_OF_DOCS
 
 _selected () {
     local dummy choice i
-    local -a selected_choices
+    local -a selected_choices valid_choices
 
     select dummy in "$@"; do  # present numbered choices to user
 # Parse ,-separated numbers entered into an array.
 # Variable $REPLY contains whatever the user entered.
         IFS=', ' read -ra selected_choices <<<"$REPLY"
 # Loop over all numbers entered.
+
+        if ! (( ${#selected_choices[*]} )); then
+            echo "No selections from menu.  'quit' or '0' for no selection." >&2
+            continue 2 # ==> continue to select
+        fi
+
         for choice in "${selected_choices[@]}"; do
 
 # hack to force easier termination
-            if [ "$choice" = 'quit' ]
+            if [ "$choice" = 'quit' ] || [ "$choice" = '0' ]
             then
                 return
             fi
@@ -96,15 +110,21 @@ _selected () {
             # reject non natural numbers
             if [ -n "${choice//[0-9]}" ] || ! (( choice >= 1 && choice <= $# ))
             then 
-                echo "Invalid choice: $choice. Try again." >&2
-                continue 2 # ==> continue to select
+                if [ "$choice" = '*' ] && ! ((is_numeric_choice)) ; then
+                    valid_choices+=($(seq -s' ' 1 $#))
+                else
+                    echo "Invalid choice: $choice. Try again." >&2
+                    continue 2 # ==> continue to select
+                fi
+            else
+                valid_choices+=("$choice")
             fi
         done
 
         if [[ ${is_unique##0} ]] ; then
             IFS=$'\n'
-            unique_choices=($(printf '%s\n' "${selected_choices[*]}" | sort -un))
-            if (( ${#unique_choices[@]} < ${#selected_choices[@]} )) ; then
+            unique_choices=($(printf '%s\n' "${valid_choices[@]}" | sort -un))
+            if (( ${#unique_choices[@]} < ${#valid_choices[@]} )) ; then
                 echo "Choice selected more than once with unique option enabled." >&2
                 continue 2 # ==> continue to select
             fi
@@ -112,16 +132,21 @@ _selected () {
 
         if [[ ${is_menu_sort##0} ]] ; then
             if [[ ${is_unique##0} ]] ; then
-                selected_choices=("${unique_choices[@]}")
+                valid_choices=("${unique_choices[@]}")
             else
                 IFS=$'\n'
-                selected_choices=( \
-                    $(printf '%s\n' "${selected_choices[*]}" | sort -n) \
+                valid_choices=( \
+                    $(printf '%s\n' "${valid_choices[*]}" | sort -n) \
                 )
             fi
         fi
 
-        for choice in "${selected_choices[@]}"; do
+        # is_xargs is true prolly implies ! [ -t 0 ]
+        if ((is_xargs)) && ! [ -t 0 ] ; then
+            echo # no return from terminal move to next line anyway
+        fi
+
+        for choice in "${valid_choices[@]}"; do
 # If valid, echo the choice and its number.
 #            echo "Choice #$(( ++i )): ${!choice} ($choice)"
             echo "${!choice}"
@@ -129,14 +154,16 @@ _selected () {
 # All choices are valid, exit the prompt.
         break
     done
+
+    return 0
 }
 
 selected() {
-    local is_menu_sort is_unique is_xargs is_infile parent_prog_name
-    local OPTIND opt dummy old_ifs="${IFS}"
+    local is_menu_sort is_unique is_xargs is_infile is_numeric_choice
+    local parent_prog_name OPTIND opt dummy old_ifs="${IFS}"
     local -a menu_opts ps_fields
 
-    while getopts a:sux opt; do
+    while getopts a:nsux opt; do
         case $opt in
             a)  is_infile=1
                 IFS=$'\n'
@@ -144,6 +171,9 @@ selected() {
                 IFS="${old_ifs}"
                 shift $((OPTIND-1))
                  _selected "${menu_opts[@]}"
+                ;;
+            n)  is_numeric_choice=1
+                shift $((OPTIND-1))
                 ;;
             s)  is_menu_sort=1
                 shift $((OPTIND-1))
